#!/usr/bin/env python3
"""Write a workspace's zellij layout: one tab per session in sessions.txt, then tabs.kdl.

sessions.txt, one session per line (# starts a comment):
    NAME  [FOLDER]  [TAB]
FOLDER defaults to workspace.conf's `folder` (else the home folder); TAB defaults to
NAME without workspace.conf's `strip_prefix`.

tabs.kdl, optional: extra tabs, raw KDL, added after the session tabs. `${WORKSPACE}`
in it becomes the workspace folder, so it can point at scripts kept beside it, and
`${HOME}` the home folder (zellij does not expand `~` in a layout).
"""
import os
import sys


def kdl(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_conf(ws: str) -> dict[str, str]:
    conf: dict[str, str] = {}
    path = os.path.join(ws, "workspace.conf")
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if "=" in line:
                key, value = line.split("=", 1)
                conf[key.strip()] = value.strip()
    return conf


def sessions(ws: str, conf: dict[str, str]):
    default_folder = os.path.expanduser(conf.get("folder", "~"))
    prefix = conf.get("strip_prefix", "")
    for line in open(os.path.join(ws, "sessions.txt"), encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        name = parts[0]
        folder = os.path.expanduser(parts[1]) if len(parts) > 1 else default_folder
        tab = parts[2] if len(parts) > 2 else (name[len(prefix):] if prefix and name.startswith(prefix) else name)
        yield name, folder, tab


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def zjstatus_path() -> str:
    data = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
    return os.path.join(data, "czw", "plugins", "zjstatus.wasm")


def timezone() -> str:
    if os.environ.get("TZ"):
        return os.environ["TZ"].lstrip(":")
    try:
        return open("/etc/timezone", encoding="utf-8").read().strip() or "UTC"
    except OSError:
        link = os.path.realpath("/etc/localtime")
        return link.split("zoneinfo/", 1)[1] if "zoneinfo/" in link else "UTC"


def bar(session: str) -> str:
    """The bar pane: zjstatus when installed (make plugins), else zellij's compact bar."""
    plugin = zjstatus_path()
    if not os.path.exists(plugin):
        return 'plugin location="zellij:compact-bar"'
    text = open(os.path.join(ROOT, "share", "bar.kdl"), encoding="utf-8").read()
    for key, value in (("@ZJSTATUS@", plugin), ("@CZW@", os.path.join(ROOT, "bin", "czw")),
                       ("@SESSION@", session), ("@TZ@", timezone()),
                       ("@STATUS@", os.path.join(os.environ.get("XDG_STATE_HOME") or os.path.expanduser("~/.local/state"),
                                                 "czw", "status", session))):
        text = text.replace(key, value)
    return "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("//"))


def template(session: str) -> str:
    inner = "\n".join("            " + l for l in bar(session).splitlines())
    return (
        "    default_tab_template {\n"
        "        children\n"
        "        pane size=1 borderless=true {\n" + inner + "\n"
        "        }\n"
        "    }\n"
    )


def session_name(ws: str, conf: dict[str, str]) -> str:
    return conf.get("name") or os.path.basename(ws)


def build(ws: str) -> str:
    conf = read_conf(ws)
    tabs = []
    for i, (name, folder, tab) in enumerate(sessions(ws, conf)):
        focus = " focus=true" if i == 0 else ""
        tabs.append(
            f"    tab name={kdl(tab)} cwd={kdl(folder)}{focus} {{\n"
            f"        pane command=\"czw\" name={kdl(name)} {{\n"
            f"            args \"claude\" {kdl(name)}\n"
            f"        }}\n"
            f"    }}"
        )
    extra_path = os.path.join(ws, "tabs.kdl")
    if os.path.exists(extra_path):
        extra = open(extra_path, encoding="utf-8").read().replace("${WORKSPACE}", ws).replace("${HOME}", os.path.expanduser("~"))
        tabs.append("\n".join("    " + l if l.strip() else l for l in extra.rstrip().splitlines()))
    return (
        f"// Generated by czw from {ws}/sessions.txt. Edit that, not this.\n"
        "layout {\n" + template(session_name(ws, conf)) + "\n".join(tabs) + "\n}\n"
    )


def write(out: str, text: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)


def main() -> None:
    args = sys.argv[1:]
    if len(args) == 3 and args[0] == "--default":
        # The layout new tabs get (Alt g, t, n): a shell with the same bar.
        write(args[1], "layout {\n" + template(args[2]) + "    pane\n}\n")
    elif len(args) == 5 and args[0] == "--tab":
        # One Claude tab, for `czw new`: NAME FOLDER TAB SESSION, printed.
        name, folder, tab, session = args[1:]
        print("layout {\n" + template(session)
              + f"    tab name={kdl(tab)} cwd={kdl(folder)} {{\n"
              + f"        pane command=\"czw\" name={kdl(name)} {{\n            args \"claude\" {kdl(name)}\n        }}\n    }}\n}}")
    elif len(args) == 2:
        write(args[1], build(os.path.abspath(args[0])))
    else:
        sys.exit("usage: layout.py WORKSPACE_DIR OUT.kdl | --default OUT SESSION | --tab NAME FOLDER TAB SESSION")


if __name__ == "__main__":
    main()
