#!/usr/bin/env python3
"""Write a workspace's zellij layout: one tab per session in sessions.txt, then tabs.kdl.

sessions.txt, one session per line (# starts a comment):
    NAME  [FOLDER]  [TAB]
FOLDER defaults to workspace.conf's `folder` (else the home folder); TAB defaults to
NAME without workspace.conf's `strip_prefix`.

tabs.kdl, optional: extra tabs, raw KDL, added after the session tabs. `${WORKSPACE}`
in it becomes the workspace folder, so it can point at scripts kept beside it, and
`${HOME}` the home folder (zellij does not expand `~` in a layout).
"""
import os
import sys


def kdl(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_conf(ws: str) -> dict[str, str]:
    conf: dict[str, str] = {}
    path = os.path.join(ws, "workspace.conf")
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if "=" in line:
                key, value = line.split("=", 1)
                conf[key.strip()] = value.strip()
    return conf


def sessions(ws: str, conf: dict[str, str]):
    default_folder = os.path.expanduser(conf.get("folder", "~"))
    prefix = conf.get("strip_prefix", "")
    for line in open(os.path.join(ws, "sessions.txt"), encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        name = parts[0]
        folder = os.path.expanduser(parts[1]) if len(parts) > 1 else default_folder
        tab = parts[2] if len(parts) > 2 else (name[len(prefix):] if prefix and name.startswith(prefix) else name)
        yield name, folder, tab


def build(ws: str) -> str:
    conf = read_conf(ws)
    tabs = []
    for i, (name, folder, tab) in enumerate(sessions(ws, conf)):
        focus = " focus=true" if i == 0 else ""
        tabs.append(
            f"    tab name={kdl(tab)} cwd={kdl(folder)}{focus} {{\n"
            f"        pane command=\"czw\" name={kdl(name)} {{\n"
            f"            args \"claude\" {kdl(name)}\n"
            f"        }}\n"
            f"    }}"
        )
    extra_path = os.path.join(ws, "tabs.kdl")
    if os.path.exists(extra_path):
        extra = open(extra_path, encoding="utf-8").read().replace("${WORKSPACE}", ws).replace("${HOME}", os.path.expanduser("~"))
        tabs.append("\n".join("    " + l if l.strip() else l for l in extra.rstrip().splitlines()))
    return (
        f"// Generated by czw from {ws}/sessions.txt. Edit that, not this.\n"
        "layout {\n"
        "    default_tab_template {\n"
        "        children\n"
        "        pane size=1 borderless=true {\n"
        "            plugin location=\"zellij:compact-bar\"\n"
        "        }\n"
        "    }\n" + "\n".join(tabs) + "\n}\n"
    )


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit("usage: layout.py WORKSPACE_DIR OUT.kdl")
    ws, out = os.path.abspath(sys.argv[1]), sys.argv[2]
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(build(ws))


if __name__ == "__main__":
    main()
